name: CI Pipeline
on:
  pull_request:
    branches: [main]
  repository_dispatch:
    types: ['prod_deployment']
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.x]
    steps:
      - name: Before Checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo '${{ toJSON(github) }}'
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Build Images
        run: echo "Build images"
      - name: Deploy to Production
        run: "Deploy to Production"
      - name: Notification When Success
        if: github.event_name == 'repository_dispatch' && github.ref == 'refs/heads/main' && success()
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://13.212.67.85:9000/api/v1/actions/status/${{ github.event.client_payload.actionId }}/CD?status=SUCCESS'
          method: 'PUT'
          username: ${{ secrets.RISK_USER }}
          password: ${{ secrets.RISK_PASSWORD }}
          customHeaders: '{"Content-Type": "application/json"}'
      - name: Notification When Failed
        if: github.event_name == 'repository_dispatch' && github.ref == 'refs/heads/main' && failure()
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://13.212.67.85:9000/api/v1/actions/status/${{ github.event.client_payload.actionId }}/CD?status=FAILED'
          method: 'PUT'
          username: ${{ secrets.RISK_USER }}
          password: ${{ secrets.RISK_PASSWORD }}
          customHeaders: '{"Content-Type": "application/json"}' 