name: CI
on:
  pull_request:
    # types:
    #   - closed
    #   - opened
    branches: [develop]
  push:
    branches: [develop]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
      - name: Install Dependency
        run: npm install
      - run: npm run prettier
      - name: Run Test
        # run: npm test -- --coverage
        run: echo "Run test"
        env: 
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
        timeout-minutes: 10
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: echo "deloy to Surge"