name: CICD for Develop Deployment
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
      - name: Install Dependency
        run: npm install
      - name: Run Prettier to check format code
        run: npm run prettier
      - name: Run Unit Test
        # run: npm test -- --coverage
        run: echo "Run test"
        env: 
          CI: true
      # - name: Upload Test Coverage 
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     # path: path/**/[abc]rtifac?/*
      #     path: coverage
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
        timeout-minutes: 10
      - name: Upload Build Folder
        if: github.event_name == 'push' 
        uses: actions/upload-artifact@v3
        with:
          name: build
          # path: path/**/[abc]rtifac?/*
          path: build
      # - name: Download Artifact
      #   if: github.event_name == 'push'
      #   uses: actions/download-artifact@v3
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: echo "deloy to Surge"
      # - name: Deploy to Heroku
      #   if: >-
      #     github.event_nam == 'push' && github.ref == 'ref/heads/develop'
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.API_HEROKU_TOKEN}}
      #     heroku_app_name: $app_name #Must be unique in Heroku
      #     heroku_email: $my_email
      #     usedocker: true
      #   env:
      #     app_name: risk-investigation
      #     my_email: minh.ht173259@sis.hust.edu.vn